# Generated by Django 5.2.1 on 2025-05-27 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 27, 7, 30, 47, 649701, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
